package main

import (
	"embed"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/wailsapp/wails/v2"
	"github.com/wailsapp/wails/v2/pkg/options"
	"github.com/wailsapp/wails/v2/pkg/options/assetserver"
	"github.com/wailsapp/wails/v2/pkg/options/windows"
)

//go:embed frontend/dist
var assets embed.FS

type LocalFileHandler struct {
	http.Handler
}

func (h *LocalFileHandler) ServeHTTP(res http.ResponseWriter, req *http.Request) {
	// Clean the URL path using logical '/' path cleaning (platform-independent)
	cleanPath := path.Clean(req.URL.Path)

	// Unescape URL encoding (e.g. %20 -> space)
	if unescaped, err := url.PathUnescape(cleanPath); err == nil {
		cleanPath = unescaped
	}

	fmt.Printf("[LocalFileHandler] HTTP Request: %s -> cleanPath: %s\n", req.URL.Path, cleanPath)

	var targetPath string

	// Check if it starts with "/local-file/" (usually Windows paths generated by frontend)
	const localFilePrefix = "/local-file/"
	if strings.HasPrefix(cleanPath, localFilePrefix) {
		filePath := strings.TrimPrefix(cleanPath, localFilePrefix)
		parts := strings.SplitN(filePath, "/", 2)
		if len(parts) == 2 {
			driveLetter := parts[0]
			restPath := filepath.FromSlash(parts[1])
			targetPath = driveLetter + ":\\" + restPath
		} else {
			targetPath = filePath
		}
	} else {
		// For standard files and non-Windows absolute paths, convert cleanPath to OS-specific path format
		targetPath = filepath.FromSlash(cleanPath)
	}

	fmt.Printf("[LocalFileHandler] Checking targetPath: %s\n", targetPath)

	if _, err := os.Stat(targetPath); err == nil {
		fmt.Printf("[LocalFileHandler] File found, serving: %s\n", targetPath)
		if strings.HasSuffix(strings.ToLower(targetPath), ".pdf") {
			res.Header().Set("Content-Type", "application/pdf")
		}
		http.ServeFile(res, req, targetPath)
		return
	}

	// Fallback: on macOS/Linux, absolute paths must start with a slash
	if !filepath.IsAbs(targetPath) && strings.HasPrefix(cleanPath, "/") {
		altPath := "/" + targetPath
		if _, err := os.Stat(altPath); err == nil {
			fmt.Printf("[LocalFileHandler] File found (alt), serving: %s\n", altPath)
			if strings.HasSuffix(strings.ToLower(altPath), ".pdf") {
				res.Header().Set("Content-Type", "application/pdf")
			}
			http.ServeFile(res, req, altPath)
			return
		}
	}

	fmt.Printf("[LocalFileHandler] File NOT found: %s\n", targetPath)
	res.WriteHeader(http.StatusNotFound)
}

func main() {
	logFile, _ := os.OpenFile(filepath.Join(os.TempDir(), "teledrive.log"), os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0666)
	os.Stdout = logFile
	os.Stderr = logFile

	app := NewApp()

	err := wails.Run(&options.App{
		Title:            "Awd TeleDrive",
		Width:            1200,
		Height:           800,
		MinWidth:         900,
		MinHeight:        600,
		AssetServer: &assetserver.Options{
			Assets:  assets,
			Handler: &LocalFileHandler{},
		},
		BackgroundColour: &options.RGBA{R: 240, G: 244, B: 249, A: 1},
		OnStartup:        app.startup,
		OnShutdown:       app.shutdown,
		OnBeforeClose:    app.BeforeClose,
		DragAndDrop: &options.DragAndDrop{
			EnableFileDrop:       true,
			DisableWebViewDrop:   true,
		},
		Bind: []interface{}{
			app,
		},
		Windows: &windows.Options{
			WebviewIsTransparent: false,
			WindowIsTranslucent:  false,
			DisableWindowIcon:    false,
		},
	})
	if err != nil {
		panic(err)
	}
}
