// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRecentFile(arg1:main.DriveItem,arg2:string):Promise<void>;

export function AddSyncTask(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CancelQRLogin():Promise<void>;

export function CheckAuth():Promise<boolean>;

export function CheckForUpdates():Promise<main.VersionCheckResult>;

export function ClearCache():Promise<Record<string, any>>;

export function ClearRecentFiles():Promise<Record<string, any>>;

export function ClearTelephotoCache():Promise<Record<string, any>>;

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function CreateWebShare(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:string):Promise<main.WebShareItem>;

export function DeleteFile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DeleteWebShare(arg1:string):Promise<boolean>;

export function DownloadFile(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Record<string, any>>;

export function DownloadFolder(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DownloadTelephotoFile(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean,arg6:string):Promise<Record<string, any>>;

export function ExportManifest():Promise<Record<string, any>>;

export function GetAPICredentials():Promise<main.AppConfig>;

export function GetAppVersion():Promise<string>;

export function GetChannelParticipants(arg1:string):Promise<Array<Record<string, any>>>;

export function GetFiles(arg1:string):Promise<Array<main.DriveItem>>;

export function GetFilesPage(arg1:string,arg2:number):Promise<main.PageResult>;

export function GetFolderInviteLink(arg1:string):Promise<string>;

export function GetFolders():Promise<Array<main.DriveItem>>;

export function GetLocalIPAddress():Promise<string>;

export function GetMediaFiles():Promise<Array<main.DriveItem>>;

export function GetMountedVirtualDrives():Promise<Array<main.MountedDriveInfo>>;

export function GetRecentFiles():Promise<Array<main.RecentItem>>;

export function GetSettings():Promise<Record<string, any>>;

export function GetShareLink(arg1:string):Promise<Record<string, any>>;

export function GetStarredFiles():Promise<Array<main.DriveItem>>;

export function GetStorageStats():Promise<main.StorageStats>;

export function GetTelephotoCacheDir():Promise<string>;

export function GetTelephotoThumbnail(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function GetThumbnail(arg1:string,arg2:string):Promise<string>;

export function GetTotalSize():Promise<number>;

export function GetTunnelPublicUrl():Promise<string>;

export function GetVirtualDriveStatus():Promise<main.VirtualDriveStatus>;

export function GetWebServerPort():Promise<number>;

export function GetWebShares():Promise<Array<main.WebShareItem>>;

export function ImportManifest():Promise<Record<string, any>>;

export function ImportTelephotoBackup(arg1:string,arg2:string):Promise<Array<main.TelephotoMediaItem>>;

export function IsStartupEnabled():Promise<boolean>;

export function IsTunnelRunning():Promise<boolean>;

export function LogDebug(arg1:string):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Logout():Promise<Record<string, any>>;

export function MountVirtualDrive(arg1:string,arg2:string):Promise<main.MountedDriveInfo>;

export function MoveFile(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function MoveFolder(arg1:string,arg2:string):Promise<Record<string, any>>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenMultiFileDialog():Promise<Array<string>>;

export function OpenReleaseURL(arg1:string):Promise<void>;

export function PreviewFile(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function PreviewTelephotoFile(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:string):Promise<Record<string, any>>;

export function QuitApp():Promise<void>;

export function ReadCachedImageBase64(arg1:string,arg2:string):Promise<string>;

export function RefreshFiles():Promise<Record<string, any>>;

export function RemoveSyncTask(arg1:string):Promise<Record<string, any>>;

export function RenameFile(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function RenameFolder(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SaveSyncSettings(arg1:string,arg2:number):Promise<Record<string, any>>;

export function ScanTelephotoGroups():Promise<Array<main.TelephotoGroup>>;

export function SearchFiles(arg1:string):Promise<Array<main.DriveItem>>;

export function SendCode(arg1:string):Promise<Record<string, any>>;

export function SendFileDirectly(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function SetAPICredentials(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SetAutoMountOnStartup(arg1:boolean,arg2:string):Promise<void>;

export function SetMinimizeToTray(arg1:boolean):Promise<void>;

export function SetStartup(arg1:boolean):Promise<Record<string, any>>;

export function ShowBalloonNotification(arg1:string,arg2:string):Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartAutoBackup(arg1:string,arg2:string):Promise<Record<string, any>>;

export function StartNativeWebDAVServer(arg1:number,arg2:string):Promise<string>;

export function StartQRLogin():Promise<Record<string, any>>;

export function StopAutoBackup():Promise<Record<string, any>>;

export function StopNativeWebDAVServer():Promise<void>;

export function TogglePublicTunnel(arg1:boolean):Promise<string>;

export function ToggleStar(arg1:main.DriveItem):Promise<boolean>;

export function ToggleSyncTask(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function UnmountVirtualDrive(arg1:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function UploadMultipleFiles(arg1:Array<string>,arg2:string):Promise<Record<string, any>>;
