// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentFile(arg1, arg2) {
  return window['go']['main']['App']['AddRecentFile'](arg1, arg2);
}

export function AddSyncTask(arg1, arg2) {
  return window['go']['main']['App']['AddSyncTask'](arg1, arg2);
}

export function CancelQRLogin() {
  return window['go']['main']['App']['CancelQRLogin']();
}

export function CheckAuth() {
  return window['go']['main']['App']['CheckAuth']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function ClearTelephotoCache() {
  return window['go']['main']['App']['ClearTelephotoCache']();
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3);
}

export function CreateWebShare(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateWebShare'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function DeleteWebShare(arg1) {
  return window['go']['main']['App']['DeleteWebShare'](arg1);
}

export function DownloadFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3, arg4);
}

export function DownloadFolder(arg1, arg2) {
  return window['go']['main']['App']['DownloadFolder'](arg1, arg2);
}

export function DownloadTelephotoFile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DownloadTelephotoFile'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ExportManifest() {
  return window['go']['main']['App']['ExportManifest']();
}

export function GetAPICredentials() {
  return window['go']['main']['App']['GetAPICredentials']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetChannelParticipants(arg1) {
  return window['go']['main']['App']['GetChannelParticipants'](arg1);
}

export function GetFiles(arg1) {
  return window['go']['main']['App']['GetFiles'](arg1);
}

export function GetFilesPage(arg1, arg2) {
  return window['go']['main']['App']['GetFilesPage'](arg1, arg2);
}

export function GetFolderInviteLink(arg1) {
  return window['go']['main']['App']['GetFolderInviteLink'](arg1);
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetLocalIPAddress() {
  return window['go']['main']['App']['GetLocalIPAddress']();
}

export function GetMediaFiles() {
  return window['go']['main']['App']['GetMediaFiles']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetShareLink(arg1) {
  return window['go']['main']['App']['GetShareLink'](arg1);
}

export function GetStarredFiles() {
  return window['go']['main']['App']['GetStarredFiles']();
}

export function GetStorageStats() {
  return window['go']['main']['App']['GetStorageStats']();
}

export function GetTelephotoCacheDir() {
  return window['go']['main']['App']['GetTelephotoCacheDir']();
}

export function GetTelephotoThumbnail(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTelephotoThumbnail'](arg1, arg2, arg3, arg4);
}

export function GetThumbnail(arg1, arg2) {
  return window['go']['main']['App']['GetThumbnail'](arg1, arg2);
}

export function GetTotalSize() {
  return window['go']['main']['App']['GetTotalSize']();
}

export function GetTunnelPublicUrl() {
  return window['go']['main']['App']['GetTunnelPublicUrl']();
}

export function GetWebServerPort() {
  return window['go']['main']['App']['GetWebServerPort']();
}

export function GetWebShares() {
  return window['go']['main']['App']['GetWebShares']();
}

export function ImportManifest() {
  return window['go']['main']['App']['ImportManifest']();
}

export function ImportTelephotoBackup(arg1, arg2) {
  return window['go']['main']['App']['ImportTelephotoBackup'](arg1, arg2);
}

export function IsStartupEnabled() {
  return window['go']['main']['App']['IsStartupEnabled']();
}

export function IsTunnelRunning() {
  return window['go']['main']['App']['IsTunnelRunning']();
}

export function LogDebug(arg1) {
  return window['go']['main']['App']['LogDebug'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MoveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2, arg3);
}

export function MoveFolder(arg1, arg2) {
  return window['go']['main']['App']['MoveFolder'](arg1, arg2);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenMultiFileDialog() {
  return window['go']['main']['App']['OpenMultiFileDialog']();
}

export function OpenReleaseURL(arg1) {
  return window['go']['main']['App']['OpenReleaseURL'](arg1);
}

export function PreviewFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewFile'](arg1, arg2, arg3);
}

export function PreviewTelephotoFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PreviewTelephotoFile'](arg1, arg2, arg3, arg4, arg5);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReadCachedImageBase64(arg1, arg2) {
  return window['go']['main']['App']['ReadCachedImageBase64'](arg1, arg2);
}

export function RemoveSyncTask(arg1) {
  return window['go']['main']['App']['RemoveSyncTask'](arg1);
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2, arg3);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function SaveSyncSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSyncSettings'](arg1, arg2);
}

export function ScanTelephotoGroups() {
  return window['go']['main']['App']['ScanTelephotoGroups']();
}

export function SearchFiles(arg1) {
  return window['go']['main']['App']['SearchFiles'](arg1);
}

export function SendCode(arg1) {
  return window['go']['main']['App']['SendCode'](arg1);
}

export function SendFileDirectly(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendFileDirectly'](arg1, arg2, arg3);
}

export function SetAPICredentials(arg1, arg2) {
  return window['go']['main']['App']['SetAPICredentials'](arg1, arg2);
}

export function SetMinimizeToTray(arg1) {
  return window['go']['main']['App']['SetMinimizeToTray'](arg1);
}

export function SetStartup(arg1) {
  return window['go']['main']['App']['SetStartup'](arg1);
}

export function ShowBalloonNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowBalloonNotification'](arg1, arg2);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartAutoBackup(arg1, arg2) {
  return window['go']['main']['App']['StartAutoBackup'](arg1, arg2);
}

export function StartQRLogin() {
  return window['go']['main']['App']['StartQRLogin']();
}

export function StopAutoBackup() {
  return window['go']['main']['App']['StopAutoBackup']();
}

export function TogglePublicTunnel(arg1) {
  return window['go']['main']['App']['TogglePublicTunnel'](arg1);
}

export function ToggleStar(arg1) {
  return window['go']['main']['App']['ToggleStar'](arg1);
}

export function ToggleSyncTask(arg1, arg2) {
  return window['go']['main']['App']['ToggleSyncTask'](arg1, arg2);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}

export function UploadMultipleFiles(arg1, arg2) {
  return window['go']['main']['App']['UploadMultipleFiles'](arg1, arg2);
}
